{{- range $sa, $value := .Values.serviceAccounts }}
{{- range $projectRoles, $role := $value.roles }}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: role-{{ $sa }}-{{ randNumeric 5}}
  namespace: nth-subset-372600
spec:
  member: serviceAccount:{{ $sa }}@nth-subset-372600.iam.gserviceaccount.com
  role: roles/{{ $role }}
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1  
    kind: Project
    external: projects/nth-subset-372600
{{- end }}    
{{- end }}
