{{- range $key, $value := .Values.serviceAccounts }}
{{ if eq $value.create true }}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: {{ $key }}
  namespace: nth-subset-372600
spec:
  displayName: {{ $value.displayName }}
{{ end }}  
{{- end }}
