global:
  projectId: apples-123
  clusterName: gke-cluster-dev

# VPC configuration
vpc-subnet:
  subnet:
    region: us-west1

# GKE Standard cluster configuration
gke-standard:

  cluster:
    location: us-west1-a
    # Private cluster configuration
    privateClusterConfig:
      enablePrivateEndpoint: true
      enablePrivateNodes: true
      masterGlobalAccessConfig:
        enabled: true
      masterIpv4CidrBlock: 10.254.0.0/28
    # Authorized networks
    masterAuthorizedNetworksConfig:
      cidrBlock: 10.2.0.0/16
      displayName: 'Authorized networks'
    enableIntranodeVisibility: true
    enableBinaryAuthorization: true
    
# Node pool 1 configuration
gke-nodepool:
  nodePool:
    location: us-west1-a
    autoscaling:
      minNodeCount: 1
      maxNodeCount: 1
    nodeConfig:
      machineType:
      diskType:
      diskSizeGb:

# Node pool 2 configuration
gke-safenodepool:
  nodePool:
    name: encrypted-nodepool
    location: us-west1-a
    autoscaling:
      minNodeCount: 1
      maxNodeCount: 1
    nodeConfig:
      machineType:
      diskType:
      diskSizeGb:
      bootDiskKMSCryptoKeyRef: "projects/nth-subset-372600/locations/us-west1/keyRings/kmskeyring-sample/cryptoKeys/kmscryptokey-sample"

# Node pool 3 configuration
gke-safenodepool-2:
  nodePool:
    name: encrypted-nodepool-2
    location: us-west1-a
    autoscaling:
      minNodeCount: 1
      maxNodeCount: 1
    nodeConfig:
      machineType: n1-standard-2
      diskType: pd-standard
      diskSizeGb: 50
      bootDiskKMSCryptoKeyRef: "projects/nth-subset-372600/locations/us-west1/keyRings/kmskeyring-sample/cryptoKeys/kmscryptokey-sample"
      enableSecureBoot: true
      enableIntegrityMonitoring: true
      serviceAccountRef: folder-admin@nth-subset-372600.iam.gserviceaccount.com