serviceAccounts:
  argocd:
    create: true
    displayName: Argo CD service account
    projectRoles:
      - owner      
  crossplane:
    create: true  
    displayName: Crossplane service account
    projectRoles:
      - owner
      - editor
  folder-admin:
    create: false
    folderRoles:
      - resourcemanager.projectCreator