# Config Connector Service Account permissions
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: iam-owner-kcc-tenant-a-123
  namespace: glassy-strata-370122
spec:
  member: serviceAccount:config-connector@glassy-strata-370122.iam.gserviceaccount.com	
  role: roles/owner
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/tenant-a-123
---
# Config Connector Service Account Workload Identity
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: configconnector-workloadidentity
  namespace: glassy-strata-370122
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    external: projects/glassy-strata-370122/serviceAccounts/config-connector@glassy-strata-370122.iam.gserviceaccount.com
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - serviceAccount:glassy-strata-370122.svc.id.goog[cnrm-system/cnrm-controller-manager-glassy-strata-370122]
        - serviceAccount:glassy-strata-370122.svc.id.goog[cnrm-system/cnrm-controller-manager-tenant-a-123]
