# Config Connector Service Account permissions
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: iam-owner-kcc-tenant-a-123
  namespace: glassy-strata-370122
spec:
  member: serviceAccount:config-connector@glassy-strata-370122.iam.gserviceaccount.com	
  role: roles/owner
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/tenant-a-123
---

# Config Connector Service Account Workload Identity
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: configconnector-workloadidentity
  namespace: glassy-strata-370122
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    external: projects/glassy-strata-370122/serviceAccounts/config-connector@glassy-strata-370122.iam.gserviceaccount.com
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - serviceAccount:glassy-strata-370122.svc.id.goog[cnrm-system/cnrm-controller-manager-glassy-strata-370122]
        - serviceAccount:glassy-strata-370122.svc.id.goog[cnrm-system/cnrm-controller-manager-tenant-a-123]
        - serviceAccount:glassy-strata-370122.svc.id.goog[cnrm-system/cnrm-controller-manager-tenant-b-123]
---

# GKE Hub Servie Agent roles
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: iam-sa-gkehub-glassy-strata
  namespace: glassy-strata-370122
spec:
  member: serviceAccount:service-408298666472@gcp-sa-gkehub.iam.gserviceaccount.com
  role: roles/gkehub.serviceAgent
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/glassy-strata-370122
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: iam-sa-gkehub-tenant-b-123
  namespace: glassy-strata-370122
spec:
  member: serviceAccount:service-408298666472@gcp-sa-gkehub.iam.gserviceaccount.com
  role: roles/gkehub.serviceAgent
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/tenant-b-123
---

# Argo CD Service Account
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: argocd
  namespace: glassy-strata-370122 
spec:
  displayName: Argo CD Service Account
---

# Argo CD Roles
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: iam-owner-argocd
  namespace: glassy-strata-370122 
spec:
  member: serviceAccount:argocd@glassy-strata-370122.iam.gserviceaccount.com	
  role: roles/owner
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/glassy-strata-370122
---

# Argo CD Roles
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: iam-owner-argocd-tenant-b-123
  namespace: glassy-strata-370122 
spec:
  member: serviceAccount:argocd@glassy-strata-370122.iam.gserviceaccount.com	
  role: roles/owner
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/tenant-b-123

---
  # Argo CD Workload Identity
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: argocd-workloadidentity
  namespace: glassy-strata-370122  
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: argocd
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - serviceAccount:glassy-strata-370122.svc.id.goog[argocd/argocd-server]
        - serviceAccount:glassy-strata-370122.svc.id.goog[argocd/argocd-application-controller]
        - serviceAccount:glassy-strata-370122.svc.id.goog[argocd/argo-cd-argocd-repo-server]