apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: iam-owner-kcc-tenant-a-123
  namespace: glassy-strata-370122
spec:
  member: serviceAccount:config-connector@glassy-strata-370122.iam.gserviceaccount.com	
  role: roles/owner
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/tenant-a-123
