apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  #annotations:
    #cnrm.cloud.google.com/project-id: hallowed-object-367706
  name: config-connector
spec:
  displayName: Service Account for Config Connector

---
# Config Connector Service Account configuration

## Workload Identity
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: workloadidentity-configconnector
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: config-connector
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - hallowed-object-367706.svc.id.goog[cnrm-system/cnrm-controller-manager-hallowed-object-367706]
        - serviceAccount:hallowed-object-367706.svc.id.goog[cnrm-system/cnrm-controller-manager-tenant-c]
        - serviceAccount:hallowed-object-367706.svc.id.goog[cnrm-system/cnrm-controller-manager-tenant-d]