apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubMembership
metadata:
  name: {{ default "standard-cluster" .Values.cluster.name }}
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.projectHostId }}
spec:
  location: global
  endpoint:
    gkeCluster:
      resourceRef:
        name: {{ default "standard-cluster" .Values.cluster.name }}
