apiVersion: v1
kind: Secret
metadata:
  name: {{ default "standard-cluster" .Values.cluster.name }}
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: {{ default "standard-cluster" .Values.cluster.name }}
  server: https://connectgateway.googleapis.com/v1/projects/{{ .Values.projectNumber }}/locations/global/gkeMemberships/{{ default "standard-cluster" .Values.cluster.name }}
  config: |
    {
      "execProviderConfig": {
        "command": "argocd-k8s-auth",
        "args": ["gcp"],
        "apiVersion": "client.authentication.k8s.io/v1beta1"
      },
      "tlsClientConfig": {
        "insecure": false,
        "caData": ""
      }
    }
