apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRouterNAT
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: dev-workloads-01
  name: computerouternat-sample-forallsubnets  
spec:
  region: us-central1
  routerRef:
    name: computerouternat-dep-forallsubnets
  natIpAllocateOption: AUTO_ONLY
  sourceSubnetworkIpRangesToNat: ALL_SUBNETWORKS_ALL_IP_RANGES
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRouter
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: dev-workloads-01
  name: computerouternat-dep-forallsubnets
spec:
  description: example router description
  region: us-central1
  networkRef:
    name: containercluster-dep-vpcnative
