# GCP Project ID
projectId: tenant-b-368823
# GCP Project Number
projectNumber: "807921000652"
# GCP Host Project ID
projectHostId: hallowed-object-367706

# VPC Configuration
vpc:
  name: network-regional
  routingMode: REGIONAL
  autoCreateSubnetworks: false

# Subnet Configuration
subnet:
  name: subnet-regional
  ipCidrRange: 10.2.0.0/16
  region: us-west1
  secondaryIpRange:
    servicesRangeName: services
    servicesIpCidrRange: 10.3.0.0/16
    podsRangeName: pods
    podsIpCidrRange: 10.4.0.0/16

# GKE Cluster Configuration
cluster:
  name: team-hubcluster-dev
  location: us-west1-a

  privateClusterConfig:
    enablePrivateEndpoint: true
    enablePrivateNodes: true
    masterGlobalAccessConfig:
      enabled: true
    masterIpv4CidrBlock: 10.254.0.0/28

  network:
    isExternal: "false"
    networkRef: network-regional
    subnetworkRef: subnet-regional

  clusterSecondaryRangeName: pods
  servicesSecondaryRangeName: services
  masterAuthorizedNetworksConfig:
    cidrBlock: 10.2.0.0/16
    displayName: 'Authorized networks'

  addonsConfig:
    configConnectorConfig:
      enabled: false
    dnsCacheConfig:
      enabled: false
    gcePersistentDiskCsiDriverConfig:
      enabled: false
    horizontalPodAutoscaling:
      disabled: true
    httpLoadBalancing:
      disabled: false
    kalmConfig:
      enabled: false
    networkPolicyConfig:
      disabled: true

  verticalPodAutoscaling:
    enabled: true

# GKE Node Pool Configuration
nodePool:
  name: custom-nodepool
  location: us-west1-a
  autoscaling:
    minNodeCount: 2
    maxNodeCount: 3
  nodeConfig:
    machineType: n1-standard-2
    diskSizeGb: 100
    diskType: pd-standard
