# -- The GCP Project ID where this cluster resides
projectId: tenant-c
cluster:
  # -- The name of this cluster
  name: team-dev
  # -- The compute location (region for a regional cluster or zone for a zonal cluster)
  location: us-central1

  privateClusterConfig:
    # -- Whether the cluster endpoint should be private
    enablePrivateEndpoint: false
    # -- Whether the cluster nodes should be private
    enablePrivateNodes: true
    # -- Enable global access to the GKE control plane's internal loab balancer.
    masterGlobalAccessConfig:
      enabled: true
    # -- Immutable. The IP range in CIDR notation to use for the hosted master network.       
    masterIpv4CidrBlock: 10.254.0.0/28

  # -- The reference to the network
  network:
    # -- Whether the network reference is external to Config Connector (non-managed)
    isExternal: "false"
    networkRef: network-regional
    # -- The reference to the subnet
    subnetworkRef: subnet-regional
  # -- The private IP range name for pods to use, this range must already exist
  clusterSecondaryRangeName: pods
  # -- The private IP range name for services to use, this range must already exist
  servicesSecondaryRangeName: services
  # -- Authorized networks
  masterAuthorizedNetworksConfig:
    cidrBlocks:
    - cidrBlock: 0.0.0.0/0
      displayName: 'Whole internet'
