apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: dev-workloads-01
  labels:
    availability: high
    target-audience: development
  name: containercluster-sample-vpcnative
spec:
  description: An autopilot regional VPC-native cluster set up with special networking considerations.
  enableAutopilot: true  
  location: us-central1
  releaseChannel:
    channel: REGULAR  
  networkingMode: VPC_NATIVE
  networkRef:
    name: containercluster-dep-vpcnative
  subnetworkRef:
    name: containercluster-dep-vpcnative
  ipAllocationPolicy:
    servicesSecondaryRangeName: servicesrange
    clusterSecondaryRangeName: clusterrange
  maintenancePolicy:
    dailyMaintenanceWindow:
      startTime: 00:00
  #enableBinaryAuthorization: true
  #enableIntranodeVisibility: true
  #enableShieldedNodes: true
  addonsConfig:
    networkPolicyConfig:
      disabled: true
    dnsCacheConfig:
      enabled: true
  networkPolicy:
    enabled: false
  podSecurityPolicyConfig:
    enabled: false
  verticalPodAutoscaling:
    enabled: true
  privateClusterConfig:
    enablePrivateEndpoint: true
    enablePrivateNodes: true
    masterIpv4CidrBlock: "10.178.213.0/28"
  masterAuthorizedNetworksConfig:
    cidrBlocks:
      - displayName: Trusted external network
        cidrBlock: 10.2.0.0/16
