gke-standard:
  projectId: tenant-d
  cluster:
    name: team-hubcluster-dev
    location: us-central1

    privateClusterConfig:
      enablePrivateEndpoint: false
      enablePrivateNodes: true
      masterGlobalAccessConfig:
        enabled: true
      masterIpv4CidrBlock: 10.254.0.0/28

    network:
      isExternal: "false"
      networkRef: network-regional
      subnetworkRef: subnet-regional

    clusterSecondaryRangeName: pods
    servicesSecondaryRangeName: services
    masterAuthorizedNetworksConfig:
      cidrBlocks:
      - cidrBlock: 0.0.0.0/0
        displayName: 'Whole internet'

    addonsConfig:
      configConnectorConfig:
        enabled: true
      dnsCacheConfig:
        enabled: true
      gcePersistentDiskCsiDriverConfig:
        enabled: true
      horizontalPodAutoscaling:
        disabled: false
      httpLoadBalancing:
        disabled: false
      kalmConfig:
        enabled: false
      networkPolicyConfig:
        disabled: true

    verticalPodAutoscaling:
      enabled: true

  nodePool:
    name: custom-nodepool
    location: us-central1
    autoscaling:
      minNodeCount: 2
      maxNodeCount: 3
    nodeConfig:
      machineType: n1-standard-2
      diskSizeGb: 100
      diskType: pd-standard
